from Standard.Base import all
import Standard.Base.Errors.Illegal_Argument.Illegal_Argument

from Standard.Test_New import all


add_specs suite_builder = suite_builder.group "Tests" group_builder->
    group_builder.specify "some property" <|
        xs = [2, 3, 4, 5]
        xs.each x->
            (x > 0).should_be_true

    group_builder.specify "other property" <|
        0.should_equal 0

    group_builder.specify "pending property" pending="This test is supposed to be ignored." <|
        0.should_equal 1

    group_builder.specify "some failing property" <|
        xs = [2, 3, 4, 5]
        xs.each x->
            x*x . should_equal 4

    group_builder.specify "something OK" <|
        1 . should_equal 1

    group_builder.specify "dataflow error" <|
        Error.throw (Illegal_Argument.Error "some error") . should_equal 0

    group_builder.specify "panic" <|
        Panic.throw (Illegal_Argument.Error "some error")

main =
    suite = Test.build suite_builder->
        add_specs suite_builder
    suite.run_with_filter

